export const EyeOfCthulhu = () => {
  return (
    <div className="relative border-8 border-double rounded border-rose-900/30 border-x-rose-900/50 h-96 w-80 overflow-hidden">
      {/* header  */}
      <span
        className=
        "absolute w-72 h-72 bg-[#747472] border-[3px] border-[#3c3c3c] rounded-full top-16 left-2 z-[2] before:content-[''] before:absolute before:w-64 before:h-64 before:bg-[#a0a0a0] before:rounded-full before:right-3  after:content-[''] after:absolute after:w-56 after:h-56 after:bg-[#d9dcd5] after:rounded-full after:right-5 after:top-2.5"></span>
      <span
        className=
        "absolute w-44 h-48 bg-[#e6e6e6] rounded-full top-20 right-12 z-[4]  before:content-[''] before:absolute before:w-32 before:h-28 before:bg-[#f5f5f5] before:rounded-full before:top-5 before:right-3 before:rotate-45"></span>

      {/* Eye  */}
      <span className="absolute w-28 h-24 bg-[#4d5acc] border-[3px] border-[#3a2524] scale-y-[.82] rounded-full bottom-[.115rem] left-[6.2rem] z-[6] before:content-[''] before:absolute before:w-24 before:h-20 before:bg-[#372ea1] before:rounded-full before:bottom-0 before:left-[5px] after:content-[''] after:absolute after:w-20 after:h-16 after:bg-[#353b19] after:rounded-full after:bottom-0 after:left-[13px]"></span>
      <span className="absolute w-16 h-14 bg-[#5d662d] scale-y-[.82] rounded-full bottom-1.5 left-[7.7rem] z-[9] before:content-[''] before:absolute before:w-14 before:h-12 before:bg-[#353827] before:rounded-full before:bottom-0 before:left-[5px] after:content-[''] after:absolute after:w-10 after:h-10 after:bg-[#141414] after:rounded-full after:bottom-0 after:left-[13px] after:scale-y-[.92]"></span>

      {/* veins */}
      <span className="absolute h-72 w-72 bg-transparent rounded-full z-[10] rotate-90 scale-y-[.97] top-24 left-2 before:content-[''] before:absolute before:h-1 before:w-32 before:rounded-sm before:bg-[#aa1f18e1] before:top-5 before:left-20 before:rotate-[21deg] after:content-[''] after:absolute after:h-1 after:w-24 after:rounded-sm after:bg-[#aa1f189a] after:bottom-2 after:left-20 after:-rotate-12" style={{ boxShadow: '-34px 0px 0 4px #aa1f18' }}></span>
      <span className="absolute h-3 w-3 bg-transparent rounded-full z-[10] bottom-[9.54rem] right-[.47rem] rotate-[71deg] before:content-[''] before:absolute before:h-1 before:w-6 before:rounded-sm before:bg-[#aa1f18] before:top-8 before:left-10 before:rotate-[40deg] after:content-[''] after:absolute after:h-1 after:w-8 after:rounded-sm after:bg-[#aa1f18d5] after:to-red-500/20 after:top-6 after:left-4 " style={{ boxShadow: '-4.6px 0px 0 .3px #aa1f18' }}></span>
      <span className="absolute h-3 w-3 bg-transparent rounded-full z-[10] bottom-[10.4rem] left-[17.9rem] rotate-[360deg] " style={{ boxShadow: '-5px 0px 0 2px #aa1f18' }}></span>

      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] rotate-[81deg] scale-x-[.80] top-28 left-10 " style={{ boxShadow: '-28px 0px 0 0px #aa1f18' }}></span>
      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] rotate-[72deg] top-20 left-32 before:content-[''] before:absolute before:bg-[#aa1f18] before:w-7 before:h-7 before:rounded-full before:top-[5.5rem] before:-left-2" style={{ boxShadow: '-28px 0px 0 0px #aa1f18' }}></span>

      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] rotate-[142deg] scale-x-[.80] top-36 left-[12.4rem] " style={{ boxShadow: '-22px 0px 0 0px #aa1f18' }}></span>
      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] rotate-[130deg] top-[5.3rem] left-[8.3rem] before:content-[''] before:absolute before:bg-[#aa1f18] before:w-7 before:h-7 before:rounded-full before:-top-[1.3rem] before:-left-[1rem]" style={{ boxShadow: '-28px 0px 0 0px #aa1f18' }}></span>

      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] scale-x-[.80] top-[7.91rem] left-[3.2rem] " style={{ boxShadow: '-22px -25px 0 0px #aa1f18' }}></span>
      <span className="absolute h-24 w-20 bg-transparent rounded-full z-[10] scale-[.4] rotate-[150deg] top-[9rem] -left-[.1rem] before:content-[''] before:absolute before:bg-[#aa1f18] before:w-9 before:h-9 before:rounded-full before:top-[6.3rem] before:-left-[1.3rem]" style={{ boxShadow: '-10px 23px 0 0px #aa1f18' }}></span>

      <span className="absolute h-24 w-1 bg-[#aa1f18c0] rounded-sm top-[10rem] left-[3.69rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-10 before:rounded before:-rotate-[23deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[2.8rem] after:left-[1.31rem] after:rotate-90"></span>
      <span className="absolute h-8 w-1 bg-transparent rounded-sm top-[14rem] left-[3.6rem] z-[10] -rotate-[180deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-10 before:rounded before:-rotate-[23deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[2.8rem] after:left-[1.31rem] after:rotate-90"></span>
      <span className="absolute h-8 w-1 bg-transparent rounded-sm top-[14rem] left-[.2rem] z-[10] -rotate-[70deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-10 before:rounded before:-rotate-[23deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[2.8rem] after:left-[1.31rem] after:rotate-90"></span>
      <span className="absolute h-8 w-1 bg-transparent rounded-sm top-[16rem] left-[2.4rem] z-[10] -rotate-[70deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-10 before:rounded before:-rotate-[23deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[2.8rem] after:left-[1.31rem] after:rotate-90"></span>
      <span className="absolute h-8 w-1 bg-transparent rounded-sm top-[13rem] left-[1.6rem] z-[10] -rotate-[40deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-10 before:rounded before:-rotate-[23deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[2.8rem] after:left-[1.31rem] after:rotate-90"></span>

      <span className="absolute h-24 w-1 bg-[#aa1f18c0] rounded-sm top-[8rem] left-[8rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-9 before:h-1 before:top-5 before:-left-1 before:rounded before:-rotate-[132deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-8 after:h-1 after:rounded after:top-[6.5rem] after:-left-[1.2rem] after:rotate-[110deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[8rem] left-[8rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-4 before:-left-5 before:rounded before:-rotate-[241deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-12 after:h-1 after:rounded after:top-[6.7rem] after:-left-[.2rem] after:rotate-[220deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[8rem] left-[8rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-20 before:-left-6 before:rounded before:-rotate-[220deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[6rem] after:left-[.8rem] after:rotate-[154deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[8rem] left-[8rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-16 before:-left-6 before:rounded before:-rotate-[180deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-10 after:h-1 after:rounded after:top-[3rem] after:rotate-[154deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[8rem] left-[8rem] z-[10] -rotate-12 before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-16 before:-left-6 before:rounded before:-rotate-[180deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-8 after:h-1 after:rounded after:top-[3rem] after:left-5 after:rotate-[184deg]"></span>

      <span className="absolute h-24 w-1 bg-[#aa1f18c0] rounded-sm top-[6rem] left-[12rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-5 before:-left-1 before:rounded before:-rotate-[132deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[6.3rem] after:-left-[1rem] after:rotate-[120deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[6rem] left-[12rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-4 before:-left-5 before:rounded before:-rotate-[241deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-12 after:h-1 after:rounded after:top-[6.7rem] after:-left-[.2rem] after:rotate-[220deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[6rem] left-[12rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-20 before:-left-6 before:rounded before:-rotate-[220deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-6 after:h-1 after:rounded after:top-[6rem] after:left-[.8rem] after:rotate-[154deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[6rem] left-[12rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-16 before:-left-6 before:rounded before:-rotate-[180deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-10 after:h-1 after:rounded after:top-[3rem] after:rotate-[154deg]"></span>
      <span className="absolute h-24 w-1 bg-transparent rounded-sm top-[6rem] left-[12rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-16 before:-left-6 before:rounded before:-rotate-[180deg] after:content-[''] after:absolute after:bg-[#aa1f18da] after:w-8 after:h-1 after:rounded after:top-[3rem] after:left-5 after:rotate-[184deg]"></span>

      <span className="absolute h-24 w-1 bg-[#aa1f18c0] rounded-sm top-[9rem] left-[16rem] z-[10] rotate-[10deg] before:content-[''] before:absolute before:bg-[#aa1f18c0] before:w-7 before:h-1 before:top-4 before:-left-5 before:rounded before:-rotate-[241deg]"></span>

      {/* Eye veins  */}
      <span className="absolute h-2 w-1 bg-[#aa1f18c0] bottom-10 left-[6.08rem] -rotate-45 z-[5] before:absolute before:h-2 before:w-1 before:bottom-2 before:left-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-3 after:left-1.5 after:rotate-90 after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-2 w-1 bg-[#aa1f18c0] bottom-6 left-[6.4rem] -rotate-45 z-[5] before:absolute before:h-2 before:w-1 before:bottom-2 before:left-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-3 after:left-1.5 after:rotate-90 after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-3 w-1 bg-[#aa1f18c0] bottom-20 left-[7.2rem] -rotate-[28deg] z-[5] before:absolute before:h-2 before:w-1 before:-bottom-1 before:left-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-[0.4rem] after:left-[.175rem] after:-rotate-[110deg] after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-4 w-1 bg-[#aa1f18c0] bottom-20 left-[9rem] -rotate-[28deg] z-[5] before:absolute before:h-6 before:w-6 before:rounded-full before:scale-x-125 before:-bottom-2 before:-left-12 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-[0.4rem] after:left-[.175rem] after:-rotate-[110deg] after:bg-[#aa1f18c0]"></span>

      <span className="absolute h-2 w-1 bg-[#aa1f18c0] bottom-10 right-[6.08rem] rotate-45 z-[5] before:absolute before:h-2 before:w-1 before:bottom-2 before:right-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-3 after:right-1.5 after:rotate-90 after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-2 w-1 bg-[#aa1f18c0] bottom-6 right-[6.4rem] -rotate-45 z-[5] before:absolute before:h-2 before:w-1 before:bottom-2 before:right-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-3 after:right-1.5 after:rotate-90 after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-3 w-1 bg-[#aa1f18c0] bottom-20 right-[7.2rem] rotate-[28deg] z-[5] before:absolute before:h-2 before:w-1 before:-bottom-1 before:right-2 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-[0.4rem] after:right-[.175rem] after:-rotate-[110deg] after:bg-[#aa1f18c0]"></span>
      <span className="absolute h-4 w-1 bg-[#aa1f18c0] bottom-20 right-[9rem] rotate-[28deg] z-[5] before:absolute before:h-6 before:w-6 before:rounded-full before:scale-x-125 before:-bottom-2 before:-right-12 before:bg-[#aa1f18c0] after:absolute after:h-2 after:w-1 after:bottom-[0.4rem] after:right-[.175rem] after:-rotate-[110deg] after:bg-[#aa1f18c0]"></span>

      {/* veins outside the body */}
      <span className="absolute h-28 w-20 bg-transparent rounded-full z-[10] rotate-[160deg] scale-y-[.97] top-4 -left-3" style={{ boxShadow: '-10px 0px 0 4px #aa1f18e1' }}></span>
      <span className="absolute h-28 w-20 bg-transparent rounded-full z-[10] rotate-[190deg] scale-y-[.97] left-8" style={{ boxShadow: '-10px 0px 0 4px #aa1f18e1' }}></span>
      <span className="absolute h-28 w-20 bg-transparent rounded-full z-[10] rotate-[20deg] scale-y-[.97] top-7 -right-3" style={{ boxShadow: '-10px 0px 0 4px #aa1f18e1' }}></span>
      <span className="absolute h-24 w-16 bg-transparent rounded-full z-[10]  scale-y-[.97] top-2 right-6" style={{ boxShadow: '-10px 0px 0 4px #aa1f18e1' }}></span>
      <span className="absolute h-24 w-16 bg-transparent rounded-full z-[10] -rotate-[20deg] scale-y-[.97] top-2 right-12" style={{ boxShadow: '-10px 0px 0 4px #aa1f18e1' }}></span>
    </div>
  )
}